# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowNDFL.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import pyodbc
import pyttsx3
from PyQt5.QtWidgets import QTableWidgetItem
from szwindow import Ui_SZForm
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NDFForm(object):

    def sayMail(self, SenderName, subject, body):  # читает почту в слух
        engine = pyttsx3.init()
        engine.say(
            "Номер служебной записки : {}, Дата : {}, Текст : {}".format(SenderName, subject, body))
        engine.runAndWait()

    def openWindow(self):  # Метод отображает дочернее окно
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SZForm()
        self.ui.setup(self.window)
        self.window.show()

        try:
            connection_to_db = pyodbc.connect(
                r'Driver={SQL Server};Server=DESKTOP-EPARK0G\SQLEXPRESS;Database=AkBarsOutlookPars;Trusted_Connection=yes;')
            cursor = connection_to_db.cursor()
            cursor.execute('SELECT * FROM szforNDFL;')  # обращение к представлению
            i = 0
            while 1:
                row = cursor.fetchone()
                if not row:
                    break

                self.ui.tableWidget.setItem(i, 0, QTableWidgetItem(row.Number_of_SZ))
                self.ui.tableWidget.setItem(i, 1, QTableWidgetItem(row.Date_of_SZ))
                self.ui.tableWidget.setItem(i, 2, QTableWidgetItem(row.Body_of_SZ))
                # self.sayMail(row.Number_of_SZ, row.Date_of_SZ, row.Body_of_SZ) читает в слух.
                i = i + 1

        except:
            print("Что-то пошло не так при подключении к MS SQL SERVER или выводу в таблицу")
        connection_to_db.close()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(928, 867)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(-10, 0, 1271, 871))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("opacity: 0.2;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("image002.png"))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(320, 110, 31, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.openWindow)  # привязка действия на кнопку по отображению окна
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "?"))
